INSERT INTO tdr."Body"("BodyId","Code","Name","Description")
VALUES
(1,'UKSC','UK Supreme Court','UK Supreme Court'),
(2,'WO','War Office','War Office'),
(3,'RF','Insolvency Service','Insolvency Service'),
(4,'ASI','Al Sweady Inquiry','Al Sweady Inquiry'),
(5,'WA','Welsh Assembly Government','Welsh Assembly Government'),
(6,'RW','The National Archives','The National Archives'),
(7,'JA','Department of Health','Department of Health'),
(8,'BT','Board of Trade Companies Registration Office','Board of Trade Companies Registration Office'),
(9,'LEV','Leveson Inquiry','Leveson Inquiry'),
(10,'MINT','Royal Mint','Royal Mint'),
(11,'MM','Millennium Commission','Millennium Commission'),
(12,'ADM','Admiralty','Admiralty'),
(13,'MH','Poor Law Board','Poor Law Board'),
(14,'FCO','Foreign and Commonwealth Office','Foreign and Commonwealth Office'),
(15,'ADM','Board of Admiralty Royal Marines','Board of Admiralty Royal Marines'),
(16,'LITV','Litvinenko Inquiry','Litvinenko Inquiry'),
(17,'SH','Equal Opportunities Commission','Equal Opportunities Commission'),
(18,'SF','Statistics Commission','Statistics Commission'),
(19,'HO','Hillsborough Independent Panel','Hillsborough Independent Panel'),
(20,'BEIS','Commitee of radioactive waste management','Commitee of radioactive waste management'),
(21,'CHIL','Iraq Inquiry','Iraq Inquiry'),
(22,'LOC','International Olympic Committee','International Olympic Committee'),
(23,'DEFE','Baha Mousa Inquiry','Baha Mousa Inquiry'),
(24,'GT','General Teaching Council for England','General Teaching Council for England'),
(26,'PF','Department of National Heritage and the Department for Culture Media and Sport','Department of National Heritage and the Department for Culture Media and Sport'),
(27,'ADM','United Kingdom Hydrographic Office','United Kingdom Hydrographic Office');
