name: TDR Run Git Secrets
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@main
      - uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@main
        if: failure()
        with:
          message: ":warning: Secrets found in repository tdr-dev-documentation"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
