name: TDR Run Git Secrets
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@main
      - uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@main
        if: failure()
        with:
          message: ":warning: Secrets found in repository tdr-dev-documentation"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
